@echo off
echo Limpiando node_modules...
rmdir /s /q node_modules
echo Instalando dependencias...
call npm install
echo Limpiando y creando directorio de producción...
rmdir /s /q prod
mkdir prod
echo Compilando aplicación...
call npm run build
echo Copiando archivos de standalone...
xcopy /E /I /Y .next\standalone\* prod\
echo Creando estructura .next...
mkdir prod\.next
xcopy /E /I /Y .next\static prod\.next\static\
echo Copiando archivos públicos...
xcopy /E /I /Y public prod\public\
echo Copiando package.json...
copy package.json prod\
echo Script completado con éxito!